<?php

return [
    /**
     * Mapa de roles → permisos (nombres de ruta).
     * Cada permiso debe coincidir exactamente con el ->name() de la ruta en web.php.
     */

    'superadmin' => [
        // Acceso total vía Gate::before en AppServiceProvider
    ],

    'admin' => [
        // Dashboard
        'dashboard',
        'admin.dashboard',
        'dashboard.export',

        // Usuarios y roles (solo superadmin en la práctica, pero incluidos por completitud)
        'users.index',
        'users.create',
        'users.store',
        'users.show',
        'users.edit',
        'users.update',
        'users.destroy',
        'roles.index',
        'roles.create',
        'roles.store',
        'roles.show',
        'roles.edit',
        'roles.update',
        'roles.destroy',
        'empresa.index',
        'empresa.store',
        'activity-log.index',

        // Catálogo
        'categories.index',
        'categories.store',
        'categories.show',
        'categories.update',
        'categories.destroy',
        'categories.toggle-active',
        'brands.index',
        'brands.store',
        'brands.show',
        'brands.update',
        'brands.destroy',
        'brands.toggle-active',
        'products.index',
        'products.create',
        'products.store',
        'products.show',
        'products.edit',
        'products.update',
        'products.destroy',
        'products.toggle-active',
        'products.images.store',
        'products.images.destroy',
        'products.images.set-primary',
        'products.images.order',
        'products.barcode',
        'products.qr',
        'products.codes',
        'products.print-labels',
        'products.movements',
        'products.stock-by-warehouse',
        'suppliers.index',
        'suppliers.create',
        'suppliers.store',
        'suppliers.show',
        'suppliers.edit',
        'suppliers.update',
        'suppliers.destroy',

        // Inventario y órdenes
        'orders.index',
        'orders.create',
        'orders.store',
        'orders.show',
        'orders.edit',
        'orders.update',
        'orders.destroy',
        'orders.products',
        'orders.convert-inventory',
        'inventarios.index',
        'inventarios.show',
        'inventarios.create',
        'inventarios.store',
        'inventarios.edit',
        'inventarios.update',
        'inventarios.destroy',
        'inventarios.reconcile-all',
        'inventarios.reconcile',
        'inventarios.adjust',
        'almacenes.index',
        'almacenes.create',
        'almacenes.store',
        'almacenes.show',
        'almacenes.edit',
        'almacenes.update',
        'almacenes.destroy',

        // Puntos de venta, transferencias admin, listas de precios
        'puntos-venta.index',
        'puntos-venta.create',
        'puntos-venta.store',
        'puntos-venta.show',
        'puntos-venta.edit',
        'puntos-venta.update',
        'puntos-venta.destroy',
        'puntos-venta.set-active',
        'transferencias.dispatch',
        'transferencias.receive',
        'transferencias.cancel',
        'listas-precios.index',
        'listas-precios.create',
        'listas-precios.store',
        'listas-precios.show',
        'listas-precios.edit',
        'listas-precios.update',
        'listas-precios.destroy',
        'listas-precios.regenerar',
    ],

    'vendedor' => [
        // Rutas abiertas (no can:), listadas como referencia/documentación
        // 'ventas.index', 'ventas.create', 'ventas.store', 'ventas.show', 'ventas.edit', 'ventas.update', 'ventas.destroy',
        // 'presupuestos.index', 'presupuestos.create', 'presupuestos.store', 'presupuestos.show', 'presupuestos.edit', 'presupuestos.update', 'presupuestos.destroy',
        // 'scanner.index', 'scanner.buscar',
        // 'customers.index', 'customers.create', 'customers.store', 'customers.show', 'customers.edit', 'customers.update',
        // 'transferencias.index', 'transferencias.create', 'transferencias.store', 'transferencias.show', 'transferencias.destroy',
        // 'pagos.create', 'pagos.store', 'pagos.destroy',
        // 'entregas.index', 'entregas.create', 'entregas.store', 'entregas.show', 'entregas.marcar-entregada', 'entregas.cancelar', 'entregas.update-warehouse', 'entregas.destroy',
        // 'chat.index', 'chat.send',
        // 'profile.edit', 'profile.update', 'profile.destroy',
        // 'password.edit', 'password.update',
    ],

    'cliente' => [
        // Rutas abiertas (no can:), listadas como referencia/documentación
        // 'dashboard',
        // 'client.dashboard', 'client.profile', 'client.profile.update',
        // 'shop.index', 'shop.show',
        // 'cart.add', 'cart.index', 'cart.clear', 'cart.update', 'cart.remove',
        // 'checkout.index', 'checkout.payment', 'checkout.success', 'checkout.failure', 'checkout.pending',
        // 'user.purchases', 'payment.status',
        // 'profile.edit', 'profile.update', 'profile.destroy',
        // 'password.edit', 'password.update',
    ],
];
